basic/basic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view(),name='home'),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),
]

basic/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.OfficeListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',views.OfficeDetailView.as_view(),name='detail'),
    url(r'^create/$',views.OfficeCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.OfficeUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.OfficeDeleteView.as_view(),name='delete'),




    ]

basic/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Office(models.Model):
    name = models.CharField(max_length=250)
    empid = models.IntegerField(max_length=100,primary_key=True)
    mobile = models.IntegerField(max_length=10,unique=True)
    address = models.CharField(max_length=256)
    dept = models.CharField(max_length=100)


    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

basic/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)
from . import models
from django.urls import reverse_lazy
# Create your views here.
class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'index.html'
class OfficeListView(ListView):
    model = models.Office

class OfficeDetailView(DetailView):
    context_object_name = 'office_details'
    model = models.Office
    template_name = 'basic_app/office_detail.html'

class OfficeCreateView(CreateView):
    fields = '__all__'
    model = models.Office


class OfficeUpdateView(UpdateView):
    fields = ("name","address","dept")
    model = models.Office
class OfficeDeleteView(DeleteView):
    model = models.Office
    success_url = reverse_lazy("basic_app:list")

basic/basic_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'home' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:list' %}">Employees detail</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Add details</a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>
</html>

basic/basic_app/templates/basic_app/office_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}
<h1>Delete {{office.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:detail' pk=office.pk%} ">Cancel</a>

</form>

{% endblock %}

basic/basic_app/templates/basic_app/office_detail.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>Employees Details:</h2>
    <p>Name: {{office_details.name}}</p>
    <p>Employee ID: {{office_details.empid}}</p>
    <p>Department: {{office_details.dept}}</p>
    <p>mobile No: {{office_details.mobile}}</p>
    <p>Address : {{office_details.address}}</p>



  </div>
<div class="container">
  <p> <a class='btn btn-warning' href="{% url 'basic_app:update' pk=office_details.pk %}">Update</a>   </p>
  <p> <a class='btn btn-danger' href="{% url 'basic_app:delete' pk=office_details.pk %}">Delete</a>   </p>
</div>


{% endblock %}

basic/basic_app/templates/basic_app/office_form.html
{% extends "base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create Office
  {% else %}
  Update Office
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

basic/basic_app/templates/basic_app/office_list.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">

    <h1>Welcome to the List of Employees</h1>
      <ol>
        {% for office in office_list %}
          <h2><li><a href="{{office.empid}}/">{{office.name}}</a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}

basic/basic_app/templates/index.html
{% extends "base.html" %}

  {% block body_block %}
    <h1>Welcome to the Home page!</h1>

    <div class="jumbotron">
      <p> To add details of the employee! Click on Add details</p>
      <p>To view the list of employees! Click on Employees detail</p>


    </div>

  {% endblock %}